[project]
name = "snick"
version = "3.0.0"
description = "Text gadgets that help with indentation and a few other gizmos"
authors = [
    {name = "Tucker Beck", email ="tucker.beck@gmail.com"},
]
license = "MIT"
readme = "README.md"
license-files = ["LICENSE.md"]
requires-python = ">=3.10"

[project.urls]
homepage = "https://github.com/dusktreader/snick"
source = "https://github.com/dusktreader/snick"
changelog = "https://github.com/dusktreader/snick/blob/main/CHANGELOG.md"

[dependency-groups]
dev = [
    "basedpyright>=1.37",
    "debugpy>=1.8",
    "ipython>=8.35",
    "mkdocs>=1.6",
    "mkdocs-material>=9.5",
    "mkdocstrings[python]>=0.27",
    "mypy>=1.19",
    "pyclean>=3.5",
    "pytest>=9.0",
    "pytest-cov>=7.0",
    "pytest-pretty>=1.3",
    "pytest-random-order>=1.2",
    "ruff>=0.14",
    "typos>=1.42",
]


[tool.uv]
package = true


[tool.pytest.ini_options]
addopts = [
    "--random-order",
    "--cov=src/snick",
    "--cov-report=term-missing",
    "--cov-fail-under=85",
    "--cov-report=xml:.coverage.xml",
    "--junitxml=.junit.xml",
    "--override-ini=junit_family=legacy",
]


[tool.ruff]
line-length = 120
src = ["src/snick", "tests"]


[tool.mypy]
pretty = true
files = ["src/snick", "tests"]


[tool.basedpyright]
reportAny = false
reportExplicitAny = false


[tool.typos.default]
extend-ignore-identifiers-re = []


[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
