[project]
name = "snick"
version = "3.2.0"
description = "Text gadgets that help with indentation and a few other gizmos"
authors = [
    {name = "Tucker Beck", email ="tucker.beck@gmail.com"},
]
license = "MIT"
readme = "README.md"
license-files = ["LICENSE.md"]
requires-python = ">=3.10"
dependencies = [
    "typing_extensions>=4.0; python_version < '3.12'",
]

[project.optional-dependencies]
demo = [
    "auto-name-enum>=3.0.0",
    "rich>=14.3.1",
    "typer>=0.21.1",
]

[project.scripts]
snick-demo = "snick_demo.main:main"

[project.urls]
homepage = "https://github.com/dusktreader/snick"
source = "https://github.com/dusktreader/snick"
changelog = "https://github.com/dusktreader/snick/blob/main/CHANGELOG.md"

[dependency-groups]
dev = [
    "debugpy>=1.8",
    "ipython>=8.35",
    "pyclean>=3.5",
    "ty>=0.0.26",
    "pytest>=9.0",
    "pytest-cov>=7.0",
    "pytest-pretty>=1.3",
    "pytest-random-order>=1.2",
    "ruff>=0.14",
    "typos>=1.42",
]


[tool.uv]
package = true

[tool.uv.build-backend]
module-name = ["snick", "snick_demo"]
module-root = "src"


[tool.pytest.ini_options]
addopts = [
    "--random-order",
    "--cov=src/snick",
    "--cov-report=term-missing",
    "--cov-fail-under=100",
    "--cov-report=xml:.coverage.xml",
    "--junitxml=.junit.xml",
    "--override-ini=junit_family=legacy",
]


[tool.ruff]
line-length = 120
src = ["src/snick", "src/snick_demo", "tests", "examples"]


[tool.typos.default]
extend-ignore-identifiers-re = []


[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
